# Generated by Django 4.2.25 on 2025-10-14 17:24
#
# Les champs role, is_verified, created_at et updated_at ont été intégrés
# dans 0001_initial (db_table auth_user). Cette migration est conservée
# pour l'historique des environnements déjà migrés ; elle ne doit rien
# appliquer sur une base neuve.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = []
