# Generated by Django 4.2.25 on 2025-11-01 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue')),
                ('timezone', models.CharField(default='Europe/Paris', help_text='Fuseau horaire (ex: Europe/Paris, America/New_York)', max_length=50, verbose_name='Fuseau horaire')),
                ('date_format', models.CharField(choices=[('US', 'US (MM/DD/YYYY)'), ('EU', 'EU (DD/MM/YYYY)')], default='EU', max_length=10, verbose_name='Format de date')),
                ('number_format', models.CharField(choices=[('point', 'Point (1.234,56)'), ('comma', 'Virgule (1 234,56)')], default='comma', max_length=10, verbose_name='Format des nombres')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=10, verbose_name='Thème')),
                ('font_size', models.CharField(choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand')], default='medium', max_length=10, verbose_name='Taille de police')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
                'db_table': 'accounts_userpreferences',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de connexion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='Connexion réussie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'db_table': 'accounts_loginhistory',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='accounts_lo_user_id_3f171e_idx')],
            },
        ),
    ]
