# Generated by Django 4.2.25 on 2025-11-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano'), ('pt', 'Português'), ('ja', '日本語'), ('ko', '한국어'), ('zh', '中文')], default='fr', max_length=10, verbose_name='Langue'),
        ),
    ]
