# Generated by Django 4.2.25 on 2025-11-02 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userpreferences_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation_token', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Token d'activation email",
                'verbose_name_plural': "Tokens d'activation email",
                'db_table': 'accounts_emailactivationtoken',
                'indexes': [models.Index(fields=['token'], name='accounts_em_token_e1720d_idx'), models.Index(fields=['user', '-created_at'], name='accounts_em_user_id_8dfbfa_idx')],
            },
        ),
    ]
