# Generated by Django 4.2.25 on 2025-11-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailactivationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='email_goal_alerts',
            field=models.BooleanField(default=True, help_text='Recevoir des emails quand un objectif est atteint ou en danger', verbose_name='Alertes email pour les objectifs'),
        ),
    ]
