# Generated by Django 4.2.25 on 2025-12-07 XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_email_goal_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='sidebar_collapsed',
            field=models.BooleanField(
                default=False,
                help_text='État de la sidebar (repliée ou dépliée)',
                verbose_name='Sidebar repliée'
            ),
        ),
    ]
