# Generated by Django 4.2.25 on 2025-12-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_sidebar_collapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='hide_current_balance',
            field=models.BooleanField(default=False, help_text='Masquer le solde actuel dans le dashboard', verbose_name='Masquer le solde actuel'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='hide_initial_balance',
            field=models.BooleanField(default=False, help_text='Masquer le solde initial dans le dashboard', verbose_name='Masquer le solde initial'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='hide_mll',
            field=models.BooleanField(default=False, help_text='Masquer le Maximum Loss Limit dans les graphiques', verbose_name='Masquer le MLL'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='hide_profit_loss',
            field=models.BooleanField(default=False, help_text='Masquer les métriques de profit et perte', verbose_name='Masquer les profits/pertes'),
        ),
    ]
