# Generated by Django 4.2.25 on 2025-12-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='privacy_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides de confidentialité par contexte de page (dashboard, statistics, trades, etc.)', verbose_name='Privacy Overrides par Page'),
        ),
    ]
