# Generated by Django 4.2.25 on 2025-12-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_privacy_overrides_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='hide_current_balance',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='hide_initial_balance',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='hide_mll',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='hide_profit_loss',
        ),
    ]
