# Generated by Django 4.2.25 on 2026-01-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_privacy_boolean_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='import_guide_collapsed',
            field=models.BooleanField(blank=True, default=None, help_text="État du guide d'import dans la modale (None = première utilisation, True = replié, False = déplié)", null=True, verbose_name="Guide d'import replié"),
        ),
    ]
