# Generated by Django 4.2.25 on 2026-01-22 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_import_guide_collapsed_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='items_per_page',
            field=models.PositiveIntegerField(default=20, help_text="Nombre d'éléments à afficher par page dans les listes (1-100)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Éléments par page'),
        ),
    ]
