# Generated by Django 4.2.25 on 2026-03-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userpreferences_items_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='bias_detection_thresholds',
            field=models.JSONField(blank=True, default=dict, help_text='Seuils personnalisés pour la détection des biais comportementaux', verbose_name='Seuils de détection des biais'),
        ),
    ]
