# Generated by Django 4.2.25 on 2026-05-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_drop_bias_detection_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='default_currency',
            field=models.CharField(default='USD', help_text='Code ISO 4217 utilisé par défaut pour les nouvelles écritures débit/crédit.', max_length=3, verbose_name='Devise par défaut (rentabilité activité)'),
        ),
    ]
