# Generated by Django 4.2.25 on 2026-05-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userpreferences_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='pnl_display',
            field=models.CharField(choices=[('net', 'PnL net (après frais et commissions)'), ('gross', 'PnL brut (avant frais et commissions)')], default='net', help_text='Montants agrégés et graphiques basés sur le net ou le brut.', max_length=10, verbose_name='Affichage du PnL'),
        ),
    ]
