# Generated by Django 4.2.25 on 2026-07-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_userpreferences_topstep_api_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='market_quotes_enabled',
            field=models.BooleanField(default=False, help_text='Cours live activés explicitement par l’utilisateur sur le dashboard.', verbose_name='Bandeau cours marché activé'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='topstep_api_paused',
            field=models.BooleanField(default=True, help_text='Si activé, le journal n’appelle pas l’API TopStep (évite le conflit de session unique).', verbose_name='API TopStep en pause'),
        ),
    ]
