# Generated by Django 4.2.25 on 2026-09-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualBacktestCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=32)),
                ('timeframe', models.CharField(max_length=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('session_start', models.TimeField(blank=True, null=True)),
                ('session_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('observation_goal', models.PositiveIntegerField(blank=True, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('slippage', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('require_refusal_reason', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualBacktestStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_instrument', models.CharField(blank=True, max_length=32)),
                ('default_timeframe', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_backtest_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualBacktestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('context_rules', models.TextField(blank=True)),
                ('setup_rules', models.TextField(blank=True)),
                ('entry_rules', models.TextField(blank=True)),
                ('stop_rules', models.TextField(blank=True)),
                ('exit_rules', models.TextField(blank=True)),
                ('invalidation_rules', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('criteria_schema', models.JSONField(blank=True, default=list)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='backtest_journal.manualbackteststrategy')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ManualBacktestObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_datetime', models.DateTimeField()),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=8)),
                ('setup_valid', models.BooleanField(default=True)),
                ('trade_taken', models.BooleanField(default=True)),
                ('refusal_reason', models.TextField(blank=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('initial_stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('slippage', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('result_status', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BREAKEVEN', 'Breakeven'), ('PARTIAL', 'Partial'), ('OPEN', 'Open'), ('NOT_TAKEN', 'Not taken')], default='OPEN', max_length=16)),
                ('result_r', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('result_r_source', models.CharField(choices=[('calculated', 'Calculated'), ('manual', 'Manual')], default='calculated', max_length=16)),
                ('result_points', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('mfe', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('mae', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('criterion_values', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('screenshot_before_url', models.CharField(blank=True, max_length=2048)),
                ('screenshot_after_url', models.CharField(blank=True, max_length=2048)),
                ('sort_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='backtest_journal.manualbacktestcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_backtest_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_index', 'market_datetime', 'id'],
            },
        ),
        migrations.AddField(
            model_name='manualbacktestcampaign',
            name='strategy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='backtest_journal.manualbacktestversion'),
        ),
        migrations.AddField(
            model_name='manualbacktestcampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_backtest_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='manualbacktestversion',
            index=models.Index(fields=['strategy', '-version'], name='backtest_jo_strateg_744de8_idx'),
        ),
        migrations.AddConstraint(
            model_name='manualbacktestversion',
            constraint=models.UniqueConstraint(fields=('strategy', 'version'), name='uniq_backtest_strategy_version'),
        ),
        migrations.AddIndex(
            model_name='manualbackteststrategy',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='backtest_jo_user_id_84c944_idx'),
        ),
        migrations.AddIndex(
            model_name='manualbacktestobservation',
            index=models.Index(fields=['campaign', 'market_datetime'], name='backtest_jo_campaig_01d995_idx'),
        ),
        migrations.AddIndex(
            model_name='manualbacktestobservation',
            index=models.Index(fields=['campaign', 'trade_taken', 'result_status'], name='backtest_jo_campaig_275ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='manualbacktestobservation',
            index=models.Index(fields=['user', '-market_datetime'], name='backtest_jo_user_id_30ba8e_idx'),
        ),
        migrations.AddIndex(
            model_name='manualbacktestcampaign',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='backtest_jo_user_id_21e4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='manualbacktestcampaign',
            index=models.Index(fields=['strategy_version'], name='backtest_jo_strateg_db1ed2_idx'),
        ),
    ]
