# Generated by Django 4.2.25 on 2026-09-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbacktestobservation',
            name='context',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='manualbacktestobservation',
            name='structure',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
