# Generated by Django 4.2.25 on 2026-09-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0050_remove_market_phase_models'),
        ('backtest_journal', '0002_observation_context_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbackteststrategy',
            name='position_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_backtest_journals', to='trades.positionstrategy'),
        ),
        migrations.AddConstraint(
            model_name='manualbackteststrategy',
            constraint=models.UniqueConstraint(condition=models.Q(('position_strategy__isnull', False)), fields=('user', 'position_strategy'), name='uniq_backtest_strategy_position'),
        ),
    ]
