"""
Django settings for trading_journal_api project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=None)
if not SECRET_KEY:
    if DEBUG:
        # En développement uniquement, générer une clé aléatoire
        import secrets
        import warnings
        SECRET_KEY = secrets.token_urlsafe(50)
        warnings.warn(
            "SECRET_KEY générée automatiquement en développement. "
            "Définir SECRET_KEY dans .env pour la production.",
            UserWarning
        )
    else:
        raise ValueError(
            "SECRET_KEY doit être défini dans les variables d'environnement pour la production. "
            "Générez une clé avec: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
        )

# Configuration sécurisée des hôtes autorisés
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1' if DEBUG else '',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
)
if not ALLOWED_HOSTS and not DEBUG:
    raise ValueError("ALLOWED_HOSTS doit être défini dans les variables d'environnement pour la production")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'guardian',
    'rolepermissions',
    # Local apps
    'accounts',
    'trades',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trading_journal_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'trading_journal_api' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trading_journal_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': config('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
        'OPTIONS': {
            'options': f"-c search_path={config('DB_SCHEMA', default='public')}"
        } if config('DB_ENGINE', default='') == 'django.db.backends.postgresql' else {},
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password Hashing - Utiliser Argon2 (plus sécurisé que PBKDF2)
# Note: argon2-cffi est dans requirements.txt
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Plus sécurisé
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Dossier où Django collectera tous les fichiers statiques
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Dossier où sont placés les fichiers statiques locaux avant collectstatic
STATICFILES_DIRS = []

# En production, ajouter le répertoire build du frontend
if not DEBUG:
    frontend_static_dir = BASE_DIR.parent / 'frontend' / 'build' / 'static'
    if frontend_static_dir.exists():
        STATICFILES_DIRS.append(frontend_static_dir)

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration de sécurité pour la production
if not DEBUG:
    # Redirection HTTPS
    SECURE_SSL_REDIRECT = True
    
    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookies sécurisés
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Autres paramètres de sécurité
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Content Security Policy (CSP) - Production
    # En production, retirer unsafe-inline et unsafe-eval pour une meilleure sécurité
    SECURE_CONTENT_SECURITY_POLICY = (
        "default-src 'self'; "
        "script-src 'self'; "  # Retirer 'unsafe-inline' et 'unsafe-eval' en production
        "style-src 'self' 'unsafe-inline'; "  # Nécessaire pour certains frameworks CSS
        "img-src 'self' data: https:; "
        "font-src 'self' data:; "
        "connect-src 'self'; "
        "frame-ancestors 'none';"
    )
    
    # Referrer Policy
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
else:
    # En développement, permettre unsafe-inline pour React DevTools
    SECURE_CONTENT_SECURITY_POLICY = (
        "default-src 'self'; "
        "script-src 'self' 'unsafe-inline' 'unsafe-eval'; "
        "style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data: https:; "
        "font-src 'self' data:; "
        "connect-src 'self'; "
        "frame-ancestors 'none';"
    )

# CORS Settings
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000' if DEBUG else '',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
)
CORS_ALLOW_CREDENTIALS = True
# SÉCURITÉ : Ne jamais permettre toutes les origines, même en développement
# Utiliser CORS_ALLOWED_ORIGINS pour spécifier les origines autorisées
CORS_ALLOW_ALL_ORIGINS = False
if not CORS_ALLOWED_ORIGINS and not DEBUG:
    raise ValueError("CORS_ALLOWED_ORIGINS doit être défini dans les variables d'environnement pour la production")
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.BlacklistJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'trades.pagination.CustomPageNumberPagination',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Rate Limiting - Protection contre les attaques par force brute
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Utilisateurs non authentifiés
        'user': '1000/hour',  # Utilisateurs authentifiés
        'login': '5/minute',  # Endpoint de login (personnalisé)
        'register': '3/hour',  # Endpoint d'inscription (personnalisé)
        'activate': '10/hour',  # Endpoint d'activation (personnalisé)
        'password_reset': '3/hour',  # Réinitialisation de mot de passe (personnalisé)
    },
}

# JWT Settings - Configuration sécurisée avec déconnexion automatique et blacklist
SIMPLE_JWT = {
    # Token d'accès équilibré pour UX et sécurité (1 heure)
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    # Token de rafraîchissement plus long mais raisonnable (4 heures)
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=4),
    # Rotation automatique des tokens de rafraîchissement
    'ROTATE_REFRESH_TOKENS': True,
    # Blacklist des anciens tokens après rotation
    'BLACKLIST_AFTER_ROTATION': True,
    # Mise à jour de la dernière connexion
    'UPDATE_LAST_LOGIN': True,
    # Algorithme de signature
    'ALGORITHM': 'HS256',
    # Clé de signature
    'SIGNING_KEY': SECRET_KEY,
    # Types d'en-têtes d'authentification
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Gestion des tokens expirés
    'TOKEN_OBTAIN_SERIALIZER': 'accounts.serializers.CustomTokenObtainPairSerializer',
    # Configuration pour la déconnexion automatique
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    # Délai de grâce pour le rafraîchissement automatique (5 minutes avant expiration)
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=15),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(hours=2),
    # Configuration de la blacklist
    'BLACKLIST_TOKEN_CHECKS': [
        'rest_framework_simplejwt.token_blacklist.blacklist.check_blacklisted_token'
    ],
}

# drf-spectacular Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'KC Trading Journal API',
    'DESCRIPTION': 'API pour le journal de trading',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Django Sites Framework
SITE_ID = 1

# Authentication Backends
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

# Django-allauth Settings - SUPPRIMÉ (non utilisé)

# Role Permissions Settings
ROLEPERMISSIONS_MODULE = 'accounts.roles'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Login History Settings
# Durée de rétention de l'historique de connexion en jours (défaut: 90 jours)
# Les entrées plus anciennes seront automatiquement supprimées par la commande de nettoyage
LOGIN_HISTORY_RETENTION_DAYS = config('LOGIN_HISTORY_RETENTION_DAYS', default=90, cast=int)

# Nombre maximum d'entrées d'historique à conserver par utilisateur (None = illimité)
# Si défini, les entrées les plus anciennes seront supprimées au-delà de cette limite
def cast_max_entries(value):
    """Convertit une valeur en int ou None."""
    if not value or str(value).strip().lower() in ('none', ''):
        return None
    return int(value)

LOGIN_HISTORY_MAX_ENTRIES_PER_USER = config('LOGIN_HISTORY_MAX_ENTRIES_PER_USER', default=None, cast=cast_max_entries)

# Celery Settings
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Cache Settings
# En développement, utiliser un cache local si Redis n'est pas disponible
if DEBUG:
    try:
        import redis
        redis_url = config('REDIS_URL', default='redis://localhost:6379/1')
        if isinstance(redis_url, str):
            redis_client = redis.Redis.from_url(redis_url)
            redis_client.ping()
            # Redis est disponible, utiliser Redis
            CACHES = {
                'default': {
                    'BACKEND': 'django_redis.cache.RedisCache',
                    'LOCATION': redis_url,
                    'OPTIONS': {
                        'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    }
                }
            }
        else:
            raise ValueError("REDIS_URL must be a string")
    except (redis.ConnectionError, ImportError, Exception):
        # Redis non disponible, utiliser un cache local en mémoire
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'unique-snowflake',
            }
        }
else:
    # En production, utiliser Redis (doit être disponible)
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': config('REDIS_URL', default='redis://localhost:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }

# Logging Configuration
# Créer le répertoire de logs s'il n'existe pas
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'security': {
            'format': '[SECURITY] {asctime} {levelname} {module} {pathname}:{lineno} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'django.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'django_security.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,  # Conserver plus de backups pour la sécurité
            'formatter': 'security',
        },
    },
    'loggers': {
        'trades': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Configuration pour les URLs relatives et proxy inverses
if DEBUG:
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = None
else:
    # En production, configurer pour les proxies inverses (Apache/Nginx)
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# S'assurer que les mots de passe email ne sont pas loggés
if EMAIL_HOST_PASSWORD:
    import logging
    logging.getLogger('django.core.mail').setLevel(logging.WARNING)

# Frontend URL pour les liens d'activation
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')
