# Generated by Django 4.2.25 on 2026-05-01 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_period_days', models.PositiveIntegerField(default=15, verbose_name='Trial period (days)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing platform settings',
                'verbose_name_plural': 'Billing platform settings',
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Stripe webhook event',
                'verbose_name_plural': 'Stripe webhook events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('paused', 'Paused')], db_index=True, max_length=32)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer subscription',
                'verbose_name_plural': 'Customer subscriptions',
                'indexes': [models.Index(fields=['user', 'status'], name='billing_cus_user_id_792251_idx'), models.Index(fields=['stripe_customer_id'], name='billing_cus_stripe__509426_idx'), models.Index(fields=['stripe_subscription_id'], name='billing_cus_stripe__dd8e30_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='unique_current_subscription_per_user'),
        ),
    ]
