# Generated by Django 4.2.25 on 2026-05-16 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, help_text='Slug du fournisseur (ex. topstepx, tradovate).', max_length=64, verbose_name='Fournisseur')),
                ('external_username', models.CharField(blank=True, default='', max_length=255, verbose_name='Identifiant externe')),
                ('secrets_encrypted', models.TextField(blank=True, default='', verbose_name='Secrets chiffrés')),
                ('secrets_hint', models.JSONField(blank=True, default=dict, verbose_name='Indicateurs masqués')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Dernière connexion réussie')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_integrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Intégration API utilisateur',
                'verbose_name_plural': 'Intégrations API utilisateur',
                'db_table': 'integrations_user_api_integration',
                'indexes': [models.Index(fields=['user', 'provider'], name='integration_user_id_a007a1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userapiintegration',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='uniq_user_api_integration_provider'),
        ),
    ]
