# Generated by Django 4.2.25 on 2025-10-19 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Numéro de version de la stratégie', verbose_name='Version')),
                ('title', models.CharField(help_text='Titre de la stratégie', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description courte de la stratégie', verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archivée'), ('draft', 'Brouillon')], default='draft', max_length=20, verbose_name='Statut')),
                ('strategy_content', models.JSONField(default=dict, help_text='Contenu structuré de la stratégie', verbose_name='Contenu de la stratégie')),
                ('version_notes', models.TextField(blank=True, help_text='Notes sur les changements de cette version', verbose_name='Notes de version')),
                ('is_current', models.BooleanField(help_text="Indique si c'est la version actuelle", verbose_name='Version actuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('parent_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='trades.positionstrategy', verbose_name='Stratégie parente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_strategies', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Stratégie de Position',
                'verbose_name_plural': 'Stratégies de Position',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='trades_posi_user_id_550289_idx'), models.Index(fields=['user', 'is_current'], name='trades_posi_user_id_e4c087_idx'), models.Index(fields=['parent_strategy'], name='trades_posi_parent__88937f_idx')],
                'unique_together': {('user', 'title', 'version')},
            },
        ),
    ]
