# Generated by Django 4.2.25 on 2025-10-19 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0002_positionstrategy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positionstrategy',
            unique_together={('user', 'parent_strategy', 'version')},
        ),
    ]
