# Generated by Django 4.2.25 on 2025-10-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_positionstrategy_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionstrategy',
            name='is_current',
            field=models.BooleanField(default=True, help_text="Indique si c'est la version actuelle", verbose_name='Version actuelle'),  # type: ignore
        ),
        migrations.AlterField(
            model_name='positionstrategy',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Numéro de version de la stratégie', verbose_name='Version'),  # type: ignore
        ),
        migrations.AlterField(
            model_name='topstepimportlog',
            name='error_count',
            field=models.IntegerField(verbose_name='Erreurs'),
        ),
        migrations.AlterField(
            model_name='topstepimportlog',
            name='skipped_count',
            field=models.IntegerField(verbose_name='Doublons ignorés'),
        ),
        migrations.AlterField(
            model_name='topstepimportlog',
            name='success_count',
            field=models.IntegerField(verbose_name='Imports réussis'),
        ),
        migrations.AlterField(
            model_name='topstepimportlog',
            name='total_rows',
            field=models.IntegerField(verbose_name='Lignes totales'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='tp1_reached',
            field=models.BooleanField(help_text='Premier Take Profit atteint', verbose_name='TP1 atteint'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='tp2_plus_reached',
            field=models.BooleanField(help_text='Deuxième Take Profit ou plus atteint', verbose_name='TP2+ atteint'),
        ),
    ]
