# Generated by Django 4.2.25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_make_trading_account_required'),
    ]

    operations = [
        # Supprimer les tables inutilisées (7 tables avec 0 enregistrements)
        migrations.RunSQL(
            sql="""
            -- Supprimer les tables socialaccount (OAuth non utilisé)
            DROP TABLE IF EXISTS socialaccount_socialaccount CASCADE;
            DROP TABLE IF EXISTS socialaccount_socialapp CASCADE;
            DROP TABLE IF EXISTS socialaccount_socialapp_sites CASCADE;
            DROP TABLE IF EXISTS socialaccount_socialtoken CASCADE;
            
            -- Supprimer les tables allauth account (non utilisé)
            DROP TABLE IF EXISTS account_emailaddress CASCADE;
            DROP TABLE IF EXISTS account_emailconfirmation CASCADE;
            
            -- ATTENTION: Les tables Guardian ont été supprimées ici mais elles sont nécessaires !
            -- django-guardian est configuré dans settings.py (INSTALLED_APPS et AUTHENTICATION_BACKENDS)
            -- Ces tables sont restaurées dans la migration 0009_restore_guardian_tables.py
            -- DROP TABLE IF EXISTS guardian_groupobjectpermission CASCADE;
            -- DROP TABLE IF EXISTS guardian_userobjectpermission CASCADE;
            """,
            reverse_sql="-- Tables inutilisées supprimées (7 tables)",
        ),
    ]
