# Generated by Django 4.2.25 on 2025-10-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_restore_guardian_tables'),
        ('trades', '0009_seed_more_currencies'),
    ]

    operations = [
    ]
