# Generated by Django 4.2.25 on 2025-11-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_merge_20251030_2009'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='currency',
            new_name='trades_curr_code_5c8100_idx',
            old_name='trades_curr_code_idx',
        ),
    ]
