# Generated by Django 4.2.25 on 2025-11-07 07:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_rename_trades_curr_code_idx_trades_curr_code_5c8100_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='initial_capital',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('50000.00'), help_text='Capital de départ du compte (utilisé pour le calcul du drawdown)', max_digits=15, null=True, verbose_name='Capital initial'),
        ),
    ]
