# Generated by Django 4.2.25 on 2025-11-09 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0012_add_initial_capital_to_trading_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('pnl_total', 'PnL Total'), ('win_rate', 'Taux de Réussite (Win Rate)'), ('trades_count', 'Nombre de Trades'), ('profit_factor', 'Profit Factor'), ('max_drawdown', 'Drawdown Maximum'), ('strategy_respect', 'Respect de la Stratégie'), ('winning_days', 'Nombre de Jours Gagnants')], help_text='Type de métrique à suivre', max_length=20, verbose_name="Type d'objectif")),
                ('period_type', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel'), ('custom', 'Personnalisé')], help_text="Période de l'objectif", max_length=20, verbose_name='Type de période')),
                ('target_value', models.DecimalField(decimal_places=9, help_text='Valeur à atteindre', max_digits=18, verbose_name='Valeur cible')),
                ('current_value', models.DecimalField(decimal_places=9, default=0, help_text='Valeur actuelle (calculée automatiquement)', max_digits=18, verbose_name='Valeur actuelle')),
                ('start_date', models.DateField(help_text="Date de début de l'objectif", verbose_name='Date de début')),
                ('end_date', models.DateField(help_text="Date de fin de l'objectif", verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('active', 'En cours'), ('achieved', 'Atteint'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('priority', models.IntegerField(default=1, help_text="Priorité de l'objectif (1-5, 5 = plus important)", verbose_name='Priorité')),
                ('notes', models.TextField(blank=True, help_text="Notes et commentaires sur l'objectif", verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('trading_account', models.ForeignKey(blank=True, help_text='Compte spécifique (vide = tous les comptes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='trades.tradingaccount', verbose_name='Compte de trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_goals', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Objectif de Trading',
                'verbose_name_plural': 'Objectifs de Trading',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='trades_trad_user_id_c8631d_idx'), models.Index(fields=['user', 'period_type', 'start_date', 'end_date'], name='trades_trad_user_id_544986_idx'), models.Index(fields=['trading_account'], name='trades_trad_trading_a1c7aa_idx')],
            },
        ),
    ]
