# Generated by Django 4.2.25 on 2025-11-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_tradinggoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsteptrade',
            name='position_strategy',
            field=models.ForeignKey(blank=True, help_text='Stratégie de position utilisée pour ce trade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trades.positionstrategy', verbose_name='Stratégie de position'),
        ),
        migrations.AlterField(
            model_name='topsteptrade',
            name='strategy',
            field=models.CharField(blank=True, editable=False, help_text='Stratégie de trading utilisée (déprécié, utiliser position_strategy)', max_length=100, verbose_name='Stratégie (déprécié)'),
        ),
    ]
