# Generated by Django 4.2.25 on 2025-11-09 21:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_add_position_strategy_to_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsteptrade',
            name='point_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Valeur d'un point de mouvement pour ce contrat (ex: 20 pour NQ, 50 pour ES)", max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valeur du point'),
        ),
    ]
