# Generated by Django 4.2.25 on 2025-11-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0015_topsteptrade_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinggoal',
            name='last_achieved_alert_sent',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière alerte email envoyée pour objectif atteint', null=True, verbose_name='Dernière alerte "atteint" envoyée'),
        ),
        migrations.AddField(
            model_name='tradinggoal',
            name='last_danger_alert_sent',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière alerte email envoyée pour objectif en danger', null=True, verbose_name='Dernière alerte "en danger" envoyée'),
        ),
        migrations.AlterField(
            model_name='tradinggoal',
            name='priority',
            field=models.IntegerField(default=1, help_text="Priorité de l'objectif (1 = faible, 5 = élevée). Les objectifs avec une priorité élevée (5) apparaissent en premier dans la liste.", verbose_name='Priorité'),
        ),
    ]
