# Generated by Django 4.2.25 on 2025-11-11 21:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0016_add_goal_alert_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsteptrade',
            name='actual_risk_reward_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Risk/Reward ratio réel calculé à partir du prix de sortie', max_digits=10, null=True, verbose_name='R:R réel'),
        ),
        migrations.AddField(
            model_name='topsteptrade',
            name='planned_risk_reward_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Risk/Reward ratio prévu calculé automatiquement', max_digits=10, null=True, verbose_name='R:R prévu'),
        ),
        migrations.AddField(
            model_name='topsteptrade',
            name='planned_stop_loss',
            field=models.DecimalField(blank=True, decimal_places=9, help_text="Prix de stop loss prévu à l'entrée du trade", max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))], verbose_name='Stop Loss prévu'),
        ),
        migrations.AddField(
            model_name='topsteptrade',
            name='planned_take_profit',
            field=models.DecimalField(blank=True, decimal_places=9, help_text="Prix de take profit prévu à l'entrée du trade", max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))], verbose_name='Take Profit prévu'),
        ),
    ]
