# Generated by Django 4.2.25 on 2025-11-13 21:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0017_topsteptrade_actual_risk_reward_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait')], help_text='Type de transaction (dépôt ou retrait)', max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant de la transaction (toujours positif)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('transaction_date', models.DateTimeField(help_text='Date et heure de la transaction', verbose_name='Date de transaction')),
                ('description', models.TextField(blank=True, help_text='Description ou notes sur cette transaction', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('trading_account', models.ForeignKey(help_text='Compte de trading associé à cette transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='trades.tradingaccount', verbose_name='Compte de trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction de compte',
                'verbose_name_plural': 'Transactions de compte',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-transaction_date'], name='trades_acco_user_id_f6a9a3_idx'), models.Index(fields=['trading_account', '-transaction_date'], name='trades_acco_trading_b3ae18_idx'), models.Index(fields=['transaction_type'], name='trades_acco_transac_ad6bbb_idx')],
            },
        ),
    ]
