# Generated by Django 4.2.25 on 2025-11-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0018_accounttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='maximum_loss_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite de perte maximale. Laissez vide pour calcul automatique selon le capital initial (50K=$2K, 100K=$3K, 150K=$4.5K)', max_digits=15, null=True, verbose_name='Maximum Loss Limit (MLL)'),
        ),
        migrations.CreateModel(
            name='AccountDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date du jour de trading', verbose_name='Date')),
                ('account_balance', models.DecimalField(decimal_places=2, help_text='Solde de fin de journée (capital initial + PnL cumulé)', max_digits=15, verbose_name='Solde du compte')),
                ('account_balance_high', models.DecimalField(decimal_places=2, help_text="Solde maximum atteint jusqu'à cette date", max_digits=15, verbose_name='Solde maximum')),
                ('maximum_loss_limit', models.DecimalField(decimal_places=2, help_text='MLL calculé pour ce jour', max_digits=15, verbose_name='Maximum Loss Limit (MLL)')),
                ('mll_is_locked', models.BooleanField(default=False, help_text='Indique si le MLL est fixé au capital initial', verbose_name='MLL verrouillé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('trading_account', models.ForeignKey(help_text='Compte de trading associé à ces métriques', on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='trades.tradingaccount', verbose_name='Compte de trading')),
            ],
            options={
                'verbose_name': 'Métrique quotidienne de compte',
                'verbose_name_plural': 'Métriques quotidiennes de compte',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['trading_account', '-date'], name='trades_acco_trading_121a4a_idx'), models.Index(fields=['date'], name='trades_acco_date_6a190c_idx')],
                'unique_together': {('trading_account', 'date')},
            },
        ),
    ]
