# Generated by Django 4.2.25 on 2025-11-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0019_tradingaccount_maximum_loss_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='mll_enabled',
            field=models.BooleanField(default=True, help_text="Activer le calcul et l'affichage du Maximum Loss Limit", verbose_name='Activer le MLL'),
        ),
    ]
