# Generated by Django 4.2.25 on 2025-11-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0020_tradingaccount_mll_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='maximum_loss_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite de perte maximale (saisie manuelle)', max_digits=15, null=True, verbose_name='Maximum Loss Limit (MLL)'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='mll_enabled',
            field=models.BooleanField(default=True, help_text="Activer l'affichage du Maximum Loss Limit", verbose_name='Activer le MLL'),
        ),
    ]
