# Generated by Django 4.2.25 on 2025-11-17 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0021_alter_tradingaccount_maximum_loss_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayStrategyCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date du jour sans trade', verbose_name='Date')),
                ('strategy_respected', models.BooleanField(blank=True, help_text="Avez-vous respecté votre stratégie en n'effectuant pas de trade ?", null=True, verbose_name='Stratégie respectée')),
                ('dominant_emotions', models.JSONField(default=list, help_text='Liste des émotions ressenties pendant cette journée', verbose_name='Émotions dominantes')),
                ('session_rating', models.IntegerField(blank=True, choices=[(1, '1 - Très mauvaise'), (2, '2 - Mauvaise'), (3, '3 - Moyenne'), (4, '4 - Bonne'), (5, '5 - Excellente')], help_text='Note de 1 à 5 pour cette journée', null=True, verbose_name='Note de la session')),
                ('emotion_details', models.TextField(blank=True, help_text='Description détaillée des émotions ressenties', verbose_name='Détails des émotions')),
                ('possible_improvements', models.TextField(blank=True, help_text="Points d'amélioration identifiés", verbose_name='Améliorations possibles')),
                ('screenshot_url', models.URLField(blank=True, help_text="Lien vers l'image TradingView ou autre", verbose_name='URL Screenshot')),
                ('video_url', models.URLField(blank=True, help_text='Lien vers une vidéo YouTube ou autre', verbose_name='URL Vidéo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('trading_account', models.ForeignKey(blank=True, help_text='Compte de trading associé (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_strategy_compliances', to='trades.tradingaccount', verbose_name='Compte de trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_strategy_compliances', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compliance de Stratégie (Jour sans trade)',
                'verbose_name_plural': 'Compliances de Stratégie (Jours sans trades)',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='trades_days_user_id_96afd2_idx'), models.Index(fields=['user', '-date'], name='trades_days_user_id_83b02c_idx'), models.Index(fields=['trading_account', 'date'], name='trades_days_trading_8022a5_idx')],
                'unique_together': {('user', 'date', 'trading_account')},
            },
        ),
    ]
