# Generated by Django 4.2.25 on 2026-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0023_add_goal_direction_and_thresholds'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='daystrategycompliance',
            index=models.Index(fields=['user', 'trading_account', 'date'], name='trades_days_user_id_6f3a92_idx'),
        ),
        migrations.AddIndex(
            model_name='daystrategycompliance',
            index=models.Index(fields=['user', 'strategy_respected'], name='trades_days_user_id_ba9c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='topsteptrade',
            index=models.Index(fields=['user', 'trade_day'], name='trades_tops_user_id_1afabd_idx'),
        ),
        migrations.AddIndex(
            model_name='topsteptrade',
            index=models.Index(fields=['user', 'trading_account', 'trade_day'], name='trades_tops_user_id_efe20c_idx'),
        ),
        migrations.AddIndex(
            model_name='tradestrategy',
            index=models.Index(fields=['user', 'strategy_respected'], name='trades_trad_user_id_2cf2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='tradestrategy',
            index=models.Index(fields=['trade', 'strategy_respected'], name='trades_trad_trade_i_029132_idx'),
        ),
    ]
