# Generated by Django 4.2.25 on 2026-01-25 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0024_add_strategies_page_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom descriptif pour identifier ce template', max_length=100, verbose_name='Nom du template')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', max_length=10, verbose_name="Format d'export")),
                ('is_default', models.BooleanField(default=False, help_text='Utiliser ce template par défaut pour les exports', verbose_name='Template par défaut')),
                ('configuration', models.JSONField(default=dict, help_text="Configuration JSON des sections et options à inclure dans l'export", verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Template d'export",
                'verbose_name_plural': "Templates d'export",
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='trades_expo_user_id_c488b7_idx'), models.Index(fields=['user', 'name'], name='trades_expo_user_id_896b2d_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
