# Generated by Django 4.2.25 on 2026-03-28 19:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0026_add_profit_target_to_trading_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du tag')),
                ('color', models.CharField(default='#3B82F6', help_text='Code couleur hexadécimal (ex: #3B82F6)', max_length=7, verbose_name='Couleur')),
                ('category', models.CharField(choices=[('setup', 'Setup'), ('mistake', 'Mistake'), ('market_condition', 'Market Condition'), ('strategy', 'Strategy'), ('other', 'Other')], default='other', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_tags', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tag de Trade',
                'verbose_name_plural': 'Tags de Trades',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TradeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_criteria', models.JSONField(default=dict, help_text='Critères utilisés pour calculer ces statistiques', verbose_name='Critères de filtrage')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Total de trades')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='Trades gagnants')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='Trades perdants')),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taux de réussite (%)')),
                ('average_win', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Gain moyen')),
                ('average_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Perte moyenne')),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profit factor')),
                ('expectancy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Expectancy')),
                ('largest_win', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Plus gros gain')),
                ('largest_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Plus grosse perte')),
                ('average_duration', models.DurationField(blank=True, null=True, verbose_name='Durée moyenne')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='trades.tradingaccount', verbose_name='Compte de trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_statistics', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Statistique de Trade',
                'verbose_name_plural': 'Statistiques de Trades',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeProbabilityFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_category', models.CharField(help_text='Ex: trend, level, timing, setup', max_length=50, verbose_name='Catégorie')),
                ('factor_name', models.CharField(max_length=100, unique=True, verbose_name='Nom du facteur')),
                ('factor_type', models.CharField(choices=[('boolean', 'Boolean'), ('categorical', 'Categorical'), ('numerical', 'Numerical')], max_length=15, verbose_name='Type de facteur')),
                ('possible_values', models.JSONField(default=list, help_text='Pour les facteurs catégoriels', verbose_name='Valeurs possibles')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Facteur de Probabilité',
                'verbose_name_plural': 'Facteurs de Probabilité',
                'ordering': ['factor_category', 'factor_name'],
                'indexes': [models.Index(fields=['factor_category'], name='trades_trad_factor__0283f5_idx'), models.Index(fields=['is_active'], name='trades_trad_is_acti_325e01_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConditionalProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_set', models.JSONField(help_text='Ex: {"trend_m15": "bullish", "fibonacci_level": "50"}', verbose_name='Ensemble de conditions')),
                ('sample_size', models.IntegerField(verbose_name="Taille de l'échantillon")),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de réussite (%)')),
                ('average_rr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='R:R moyen')),
                ('expectancy', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Expectancy')),
                ('confidence_interval', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Intervalle de confiance (%)')),
                ('is_statistically_significant', models.BooleanField(default=False, help_text='True si sample_size >= 30', verbose_name='Statistiquement significatif')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_probabilities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Probabilité Conditionnelle',
                'verbose_name_plural': 'Probabilités Conditionnelles',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_assignments', to='trades.tradetag', verbose_name='Tag')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='trades.topsteptrade', verbose_name='Trade')),
            ],
            options={
                'verbose_name': 'Attribution de Tag',
                'verbose_name_plural': 'Attributions de Tags',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trade'], name='trades_trad_trade_i_c38a09_idx'), models.Index(fields=['tag'], name='trades_trad_tag_id_7fb646_idx')],
                'unique_together': {('trade', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='tradetag',
            index=models.Index(fields=['user', 'category'], name='trades_trad_user_id_112a62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradetag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='tradestatistics',
            index=models.Index(fields=['user', '-calculated_at'], name='trades_trad_user_id_b5c463_idx'),
        ),
        migrations.AddIndex(
            model_name='tradestatistics',
            index=models.Index(fields=['trading_account', '-calculated_at'], name='trades_trad_trading_250ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionalprobability',
            index=models.Index(fields=['user', '-calculated_at'], name='trades_cond_user_id_9ef1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionalprobability',
            index=models.Index(fields=['is_statistically_significant'], name='trades_cond_is_stat_ed94d4_idx'),
        ),
    ]
