# Generated by Django 4.2.25 on 2026-03-01 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0027_add_timeframe_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradetag',
            name='unique_user_tag_name',
        ),
        migrations.RemoveConstraint(
            model_name='tradetagassignment',
            name='unique_trade_tag',
        ),
        migrations.RenameIndex(
            model_name='conditionalprobability',
            new_name='trades_cond_user_id_9ef1e8_idx',
            old_name='trades_cond_user_id_idx017',
        ),
        migrations.RenameIndex(
            model_name='conditionalprobability',
            new_name='trades_cond_is_stat_ed94d4_idx',
            old_name='trades_cond_is_stat_idx018',
        ),
        migrations.RenameIndex(
            model_name='sessioncontext',
            new_name='trades_sess_trade_i_2ef563_idx',
            old_name='trades_sess_trade_i_idx006',
        ),
        migrations.RenameIndex(
            model_name='sessioncontext',
            new_name='trades_sess_trading_7a0a37_idx',
            old_name='trades_sess_trading_idx007',
        ),
        migrations.RenameIndex(
            model_name='tradecontext',
            new_name='trades_trad_trade_i_ec7a76_idx',
            old_name='trades_trad_trade_i_idx001',
        ),
        migrations.RenameIndex(
            model_name='tradecontext',
            new_name='trades_trad_trend_m_c65c6d_idx',
            old_name='trades_trad_trend_m_idx002',
        ),
        migrations.RenameIndex(
            model_name='tradecontext',
            new_name='trades_trad_trend_a_2e1e2c_idx',
            old_name='trades_trad_trend_a_idx003',
        ),
        migrations.RenameIndex(
            model_name='tradeexecution',
            new_name='trades_trad_trade_i_1c2915_idx',
            old_name='trades_trad_trade_i_idx008',
        ),
        migrations.RenameIndex(
            model_name='tradeexecution',
            new_name='trades_trad_followe_06e0bb_idx',
            old_name='trades_trad_followe_idx009',
        ),
        migrations.RenameIndex(
            model_name='tradeexecution',
            new_name='trades_trad_exit_re_bfd3f5_idx',
            old_name='trades_trad_exit_re_idx010',
        ),
        migrations.RenameIndex(
            model_name='tradeprobabilityfactor',
            new_name='trades_trad_factor__0283f5_idx',
            old_name='trades_trad_factor__idx011',
        ),
        migrations.RenameIndex(
            model_name='tradeprobabilityfactor',
            new_name='trades_trad_is_acti_325e01_idx',
            old_name='trades_trad_is_acti_idx012',
        ),
        migrations.RenameIndex(
            model_name='tradesetup',
            new_name='trades_trad_trade_i_30a6e4_idx',
            old_name='trades_trad_trade_i_idx004',
        ),
        migrations.RenameIndex(
            model_name='tradesetup',
            new_name='trades_trad_setup_c_6d3180_idx',
            old_name='trades_trad_setup_c_idx005',
        ),
        migrations.RenameIndex(
            model_name='tradestatistics',
            new_name='trades_trad_user_id_b5c463_idx',
            old_name='trades_trad_user_id_idx015',
        ),
        migrations.RenameIndex(
            model_name='tradestatistics',
            new_name='trades_trad_trading_250ab2_idx',
            old_name='trades_trad_trading_idx016',
        ),
        migrations.RenameIndex(
            model_name='tradetag',
            new_name='trades_trad_user_id_112a62_idx',
            old_name='trades_trad_user_id_idx019',
        ),
        migrations.RenameIndex(
            model_name='tradetagassignment',
            new_name='trades_trad_trade_i_c38a09_idx',
            old_name='trades_trad_trade_i_idx013',
        ),
        migrations.RenameIndex(
            model_name='tradetagassignment',
            new_name='trades_trad_tag_id_7fb646_idx',
            old_name='trades_trad_tag_id__idx014',
        ),
        migrations.AlterField(
            model_name='conditionalprobability',
            name='condition_set',
            field=models.JSONField(help_text='Ex: {"trend_m15": "bullish", "fibonacci_level": "50"}', verbose_name='Ensemble de conditions'),
        ),
        migrations.AlterField(
            model_name='conditionalprobability',
            name='is_statistically_significant',
            field=models.BooleanField(default=False, help_text='True si sample_size >= 30', verbose_name='Statistiquement significatif'),
        ),
        migrations.AlterField(
            model_name='sessioncontext',
            name='session_time_slot',
            field=models.CharField(blank=True, help_text='Ex: 09:30-10:00', max_length=20, verbose_name='Créneau horaire'),
        ),
        migrations.AlterField(
            model_name='tradecontext',
            name='atr_percentile',
            field=models.IntegerField(blank=True, help_text='ATR par rapport à la moyenne 20 jours (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ATR percentile'),
        ),
        migrations.AlterField(
            model_name='tradeexecution',
            name='execution_errors',
            field=models.JSONField(default=list, help_text='Liste des erreurs commises', verbose_name="Erreurs d'exécution"),
        ),
        migrations.AlterField(
            model_name='tradeprobabilityfactor',
            name='factor_category',
            field=models.CharField(help_text='Ex: trend, level, timing, setup', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='tradeprobabilityfactor',
            name='possible_values',
            field=models.JSONField(default=list, help_text='Pour les facteurs catégoriels', verbose_name='Valeurs possibles'),
        ),
        migrations.AlterField(
            model_name='tradesetup',
            name='confluence_factors',
            field=models.JSONField(default=list, help_text='Liste des facteurs de confirmation', verbose_name='Facteurs de confluence'),
        ),
        migrations.AlterField(
            model_name='tradesetup',
            name='setup_subcategory',
            field=models.CharField(blank=True, help_text='Ex: pullback_to_ema, breakout_consolidation', max_length=100, verbose_name='Sous-catégorie'),
        ),
        migrations.AlterField(
            model_name='tradestatistics',
            name='filter_criteria',
            field=models.JSONField(default=dict, help_text='Critères utilisés pour calculer ces statistiques', verbose_name='Critères de filtrage'),
        ),
        migrations.AlterField(
            model_name='tradetag',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Code couleur hexadécimal (ex: #3B82F6)', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AlterUniqueTogether(
            name='tradetag',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tradetagassignment',
            unique_together={('trade', 'tag')},
        ),
    ]
