# Generated by Django 4.2.25 on 2026-03-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0026_tradetag_tradestatistics_tradeprobabilityfactor_and_more'),
        ('trades', '0027_tradetag_tradestatistics_tradeprobabilityfactor_and_more'),
    ]

    operations = [
    ]
