# Generated by Django 4.2.25 on 2026-03-03 19:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0028_remove_tradetag_unique_user_tag_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncontext',
            name='minutes_since_last_trade',
            field=models.IntegerField(blank=True, help_text='Calculé automatiquement', null=True, verbose_name='Minutes depuis le dernier trade'),
        ),
        migrations.AddField(
            model_name='sessioncontext',
            name='previous_trade_result',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven'), ('first_trade_of_session', 'First Trade of Session')], max_length=25, null=True, verbose_name='Résultat du trade précédent'),
        ),
        migrations.AddField(
            model_name='sessioncontext',
            name='trade_motivation',
            field=models.CharField(blank=True, choices=[('setup_signal', 'Setup Signal'), ('fomo', 'FOMO'), ('revenge', 'Revenge'), ('boredom', 'Boredom'), ('recovery_attempt', 'Recovery Attempt'), ('planned', 'Planned')], max_length=20, null=True, verbose_name='Motivation principale du trade'),
        ),
        migrations.AddField(
            model_name='tradeexecution',
            name='exit_trigger',
            field=models.CharField(blank=True, choices=[('target_hit', 'Target Hit'), ('stop_hit', 'Stop Hit'), ('fear', 'Fear'), ('greed', 'Greed'), ('time_based', 'Time Based'), ('news', 'News'), ('manual_discretion', 'Manual Discretion'), ('break_even', 'Break Even')], help_text="Qu'est-ce qui a déclenché la sortie ?", max_length=20, null=True, verbose_name='Déclencheur de sortie'),
        ),
        migrations.AddField(
            model_name='tradeexecution',
            name='position_size_change_reason',
            field=models.TextField(blank=True, help_text='Pourquoi avez-vous modifié la taille de position ?', verbose_name='Raison du changement de taille'),
        ),
        migrations.AddField(
            model_name='tradeexecution',
            name='time_in_position_vs_planned',
            field=models.CharField(blank=True, choices=[('much_shorter', 'Much Shorter'), ('shorter', 'Shorter'), ('as_planned', 'As Planned'), ('longer', 'Longer'), ('much_longer', 'Much Longer')], help_text='Êtes-vous sorti trop tôt/tard ?', max_length=15, null=True, verbose_name='Durée en position vs plan'),
        ),
        migrations.AddField(
            model_name='tradesetup',
            name='entry_in_range_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0% = bas du range, 100% = haut du range', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name="Position d'entrée dans le range du jour (%)"),
        ),
        migrations.AddField(
            model_name='tradesetup',
            name='missed_better_entry',
            field=models.BooleanField(default=False, help_text='Avez-vous raté une meilleure entrée avant ?', verbose_name='Meilleure entrée ratée'),
        ),
        migrations.AddField(
            model_name='tradesetup',
            name='planned_hold_duration',
            field=models.IntegerField(blank=True, help_text='Combien de temps prévoyiez-vous de rester en position ?', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée prévue en position (minutes)'),
        ),
    ]
