# Generated by Django 4.2.25 on 2026-03-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0028_merge_20260328_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionstrategy',
            name='example_screenshot',
            field=models.URLField(blank=True, help_text="URL de la capture d'écran illustrant la stratégie", verbose_name="Capture d'écran d'exemple"),
        ),
        migrations.AddField(
            model_name='positionstrategy',
            name='example_screenshot_thumbnail',
            field=models.URLField(blank=True, help_text="URL de la miniature de la capture d'écran", verbose_name="Miniature de la capture d'écran"),
        ),
    ]
