# Generated by Django 4.2.25 on 2026-03-03 21:17

from django.db import migrations, models


def migrate_exit_trigger_to_emotional_context(apps, schema_editor):
    """Migrer les données de exit_trigger vers exit_emotional_context"""
    TradeExecution = apps.get_model('trades', 'TradeExecution')
    
    # Mapping direct pour fear et greed
    TradeExecution.objects.filter(exit_trigger='fear').update(exit_emotional_context='fear')
    TradeExecution.objects.filter(exit_trigger='greed').update(exit_emotional_context='greed')
    
    # Tous les autres cas (target_hit, stop_hit, time_based, news, manual_discretion, break_even) → neutral
    TradeExecution.objects.filter(
        exit_trigger__in=['target_hit', 'stop_hit', 'time_based', 'news', 'manual_discretion', 'break_even']
    ).update(exit_emotional_context='neutral')
    
    # Les trades sans exit_trigger restent à neutral (valeur par défaut)


def reverse_migration(apps, schema_editor):
    """Fonction inverse (optionnelle, pour rollback)"""
    TradeExecution = apps.get_model('trades', 'TradeExecution')
    
    # Remettre les valeurs dans exit_trigger basé sur exit_emotional_context
    TradeExecution.objects.filter(exit_emotional_context='fear').update(exit_trigger='fear')
    TradeExecution.objects.filter(exit_emotional_context='greed').update(exit_trigger='greed')
    # neutral → on ne peut pas deviner la valeur originale, on laisse null


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0029_sessioncontext_minutes_since_last_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeexecution',
            name='exit_emotional_context',
            field=models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('fear', 'Fear'), ('greed', 'Greed'), ('fomo', 'FOMO'), ('discipline', 'Discipline')], default='neutral', help_text='État émotionnel lors de la sortie', max_length=20, null=True, verbose_name='Contexte émotionnel de sortie'),
        ),
        migrations.RunPython(migrate_exit_trigger_to_emotional_context, reverse_migration),
    ]
