# Generated by Django 4.2.25 on 2026-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0029_add_example_screenshot_to_position_strategy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='positionstrategy',
            index=models.Index(fields=['user', 'status', '-created_at'], name='trades_posi_user_id_36fb13_idx'),
        ),
    ]
