# Generated by Django 4.2.25 on 2026-03-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0030_add_exit_emotional_context_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeexecution',
            name='exit_trigger',
        ),
    ]
