# Generated by Django 4.2.25 on 2026-04-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0030_add_status_index_to_positionstrategy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topsteptrade',
            index=models.Index(fields=['position_strategy'], name='trades_tops_positio_fbddb8_idx'),
        ),
        migrations.AddIndex(
            model_name='topsteptrade',
            index=models.Index(fields=['user', 'position_strategy'], name='trades_tops_user_id_bb6469_idx'),
        ),
    ]
