# Generated by Django 4.2.25 on 2026-03-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0031_remove_exit_trigger_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncontext',
            name='news_events',
            field=models.JSONField(blank=True, help_text="Liste d'événements externes avec impact et description", null=True, verbose_name='Événements externes (JSON)'),
        ),
    ]
