# Generated by Django 4.2.25 on 2026-04-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0032_alter_tradinggoal_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradinggoal',
            name='goal_type',
            field=models.CharField(choices=[('pnl_total', 'PnL Total'), ('withdrawal_amount', 'Montant des Retraits'), ('max_consecutive_losses', 'Pertes Consécutives Max'), ('daily_loss_limit_breaches', 'Dépassements Limite Perte Journalière'), ('expectancy', 'Expectancy'), ('avg_rr_actual', 'R:R Réel Moyen'), ('journal_completion_rate', 'Taux Complétion Journal'), ('win_rate', 'Taux de Réussite (Win Rate)'), ('trades_count', 'Nombre de Trades'), ('profit_factor', 'Profit Factor'), ('max_drawdown', 'Drawdown Maximum'), ('strategy_respect', 'Respect de la Stratégie'), ('winning_days', 'Nombre de Jours Gagnants')], help_text='Type de métrique à suivre', max_length=40, verbose_name="Type d'objectif"),
        ),
    ]
