# Generated by Django 4.2.25 on 2026-03-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0033_migrate_news_data_to_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioncontext',
            name='news_description',
        ),
        migrations.RemoveField(
            model_name='sessioncontext',
            name='news_event',
        ),
        migrations.RemoveField(
            model_name='sessioncontext',
            name='news_impact',
        ),
        migrations.AlterField(
            model_name='sessioncontext',
            name='news_events',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'événements externes avec impact et description", null=True, verbose_name='Événements externes'),
        ),
    ]
