# Generated by Django 4.2.25 on 2026-03-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0034_remove_old_news_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeexecution',
            name='entry_as_planned',
            field=models.BooleanField(blank=True, null=True, verbose_name='Entrée comme prévu'),
        ),
        migrations.AlterField(
            model_name='tradeexecution',
            name='exit_as_planned',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sortie comme prévu'),
        ),
        migrations.AlterField(
            model_name='tradeexecution',
            name='position_size_as_planned',
            field=models.BooleanField(blank=True, null=True, verbose_name='Taille de position comme prévu'),
        ),
    ]
