# Generated by Django 4.2.25 on 2026-05-16 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0035_alter_videourl_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=64, verbose_name='Fournisseur')),
                ('source', models.CharField(choices=[('api', 'API'), ('csv', 'CSV')], default='api', max_length=16, verbose_name='Source')),
                ('total_fetched', models.IntegerField(default=0, verbose_name='Éléments récupérés')),
                ('created_count', models.IntegerField(default=0, verbose_name='Créations')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Ignorés (doublons)')),
                ('error_count', models.IntegerField(default=0, verbose_name='Erreurs')),
                ('errors', models.JSONField(blank=True, null=True, verbose_name='Détails des erreurs')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Synchronisé le')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_sync_logs', to='trades.tradingaccount', verbose_name='Compte de trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_sync_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log de synchronisation trades',
                'verbose_name_plural': 'Logs de synchronisation trades',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['trading_account', 'provider', '-synced_at'], name='trades_trad_trading_0d0f0b_idx')],
            },
        ),
    ]
