# Generated by Django 4.2.25 on 2026-05-17 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0002_rename_daily_journ_user_id_7b6ae0_idx_daily_journ_user_id_67a455_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0036_trade_sync_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, verbose_name='Date de session')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('built', 'Construite'), ('failed', 'Échec')], default='pending', max_length=16, verbose_name='Statut')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('trade_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de trades')),
                ('net_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='PnL net session')),
                ('max_drawdown_intraday', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Drawdown intraday max')),
                ('build_error', models.TextField(blank=True, verbose_name='Erreur de construction')),
                ('built_at', models.DateTimeField(blank=True, null=True, verbose_name='Construite le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to='trades.tradingaccount', verbose_name='Compte de trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session de trading',
                'verbose_name_plural': 'Sessions de trading',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionJournalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Appliqué le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('applied_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_replay_drafts', to='daily_journal.dailyjournalentry', verbose_name='Entrée journal appliquée')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_draft', to='trades.tradingsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Brouillon journal de session',
                'verbose_name_plural': 'Brouillons journal de session',
            },
        ),
        migrations.CreateModel(
            name='SessionInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='Code')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='warning', max_length=16, verbose_name='Sévérité')),
                ('message', models.TextField(verbose_name='Message')),
                ('occurred_at', models.DateTimeField(verbose_name='Horodatage')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Contexte')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='trades.tradingsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Insight de session',
                'verbose_name_plural': 'Insights de session',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Ordre créé'), ('order_updated', 'Ordre modifié'), ('fill', 'Fill'), ('position_open', 'Position ouverte'), ('position_close', 'Position fermée'), ('pnl_tick', 'Tick PnL')], max_length=32, verbose_name='Type')),
                ('source', models.CharField(choices=[('order', 'Ordre'), ('fill', 'Fill'), ('derived', 'Dérivé')], max_length=16, verbose_name='Source')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='ID externe')),
                ('sequence', models.PositiveIntegerField(verbose_name='Séquence')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Horodatage')),
                ('payload', models.JSONField(default=dict, verbose_name='Données')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trades.tradingsession', verbose_name='Session')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_events', to='trades.topsteptrade', verbose_name='Trade lié')),
            ],
            options={
                'verbose_name': 'Événement de session',
                'verbose_name_plural': 'Événements de session',
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='tradingsession',
            index=models.Index(fields=['user', 'trading_account', '-session_date'], name='trades_trad_user_id_72d43a_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsession',
            index=models.Index(fields=['trading_account', 'session_date'], name='trades_trad_trading_cb970c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradingsession',
            unique_together={('user', 'trading_account', 'session_date')},
        ),
        migrations.AddIndex(
            model_name='sessioninsight',
            index=models.Index(fields=['session', 'occurred_at'], name='trades_sess_session_205f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioninsight',
            index=models.Index(fields=['session', 'code'], name='trades_sess_session_81870b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['session', 'sequence'], name='trades_sess_session_e2e67c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['session', 'occurred_at'], name='trades_sess_session_85a9dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionevent',
            unique_together={('session', 'source', 'external_id', 'event_type')},
        ),
    ]
