# Generated by Django 4.2.25 on 2026-06-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0038_tradingsession_market_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='balance_computed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soldes calculés le'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_best_day',
            field=models.DateField(blank=True, null=True, verbose_name='Meilleur jour TopStep (cache)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_best_day_pnl_gross',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True, verbose_name='PnL brut meilleur jour (cache)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_best_day_pnl_net',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True, verbose_name='PnL net meilleur jour (cache)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_current_balance',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True, verbose_name='Solde actuel (cache)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_current_balance_gross',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True, verbose_name='Solde actuel brut (cache)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_net_transactions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Flux nets (cache)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_peak_balance',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True, verbose_name='Pic de solde net (cache)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_peak_balance_gross',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True, verbose_name='Pic de solde brut (cache)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_total_deposits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total dépôts (cache)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='cached_total_withdrawals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total retraits (cache)'),
        ),
    ]
