# Generated by Django 4.2.25 on 2026-06-21 13:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0040_alter_tradingaccount_initial_capital_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_day', models.DateField(verbose_name='Jour de trading')),
                ('strategy_root_id', models.IntegerField(default=0, help_text='ID racine de la famille (parent_strategy_id or id). 0 = sans stratégie.', verbose_name='Racine stratégie')),
                ('pnl_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('pnl_gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('trade_count', models.PositiveIntegerField(default=0)),
                ('win_count', models.PositiveIntegerField(default=0)),
                ('loss_count', models.PositiveIntegerField(default=0)),
                ('sum_win_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('sum_loss_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('sum_duration_seconds', models.BigIntegerField(default=0)),
                ('largest_win', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('largest_loss', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rollups', to='trades.tradingaccount', verbose_name='Compte de trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_daily_rollups', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rollup journalier trade',
                'verbose_name_plural': 'Rollups journaliers trades',
                'indexes': [models.Index(fields=['user', 'trading_account', 'trade_day', 'strategy_root_id'], name='trades_rollup_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tradedailyrollup',
            constraint=models.UniqueConstraint(fields=('user', 'trading_account', 'trade_day', 'strategy_root_id'), name='trades_daily_rollup_unique'),
        ),
    ]
