# Generated by Django 4.2.25 on 2026-07-11 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0042_positionstrategy_version_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPhaseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('color', models.CharField(default='#6366F1', max_length=7, verbose_name='Couleur')),
                ('is_system', models.BooleanField(default=False, verbose_name='Système')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_phase_definitions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Définition de phase marché',
                'verbose_name_plural': 'Définitions de phases marché',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MarketPhaseEventDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('category', models.CharField(choices=[('breakout', 'Breakout'), ('reentry', 'Réintégration'), ('push', 'Poussée'), ('other', 'Autre')], default='other', max_length=16)),
                ('is_system', models.BooleanField(default=False, verbose_name='Système')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_phase_event_definitions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Définition événement phase marché',
                'verbose_name_plural': 'Définitions événements phase marché',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SessionMarketPhaseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True)),
                ('instrument_key', models.CharField(db_index=True, max_length=32)),
                ('range_start', models.TimeField()),
                ('range_end', models.TimeField(blank=True, null=True)),
                ('preceding_context', models.CharField(choices=[('none', 'Aucun'), ('after_bullish_push', 'Après poussée haussière'), ('after_bearish_push', 'Après poussée baissière'), ('after_range', 'Après range'), ('after_news', 'Après news')], default='none', max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(choices=[('live', 'Live'), ('replay', 'Replay')], default='live', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='trades.marketphasedefinition')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_phase_blocks', to='trades.tradingaccount')),
                ('trading_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_phase_blocks', to='trades.tradingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_phase_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloc phase marché',
                'verbose_name_plural': 'Blocs phases marché',
                'ordering': ['session_date', 'range_start'],
            },
        ),
        migrations.CreateModel(
            name='MarketPhaseSlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('fixed', 'Fixe'), ('custom', 'Personnalisé'), ('hour', 'Heures pleines')], default='hour', max_length=16)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('anchor', models.CharField(choices=[('market_open', 'Ouverture marché'), ('clock_hour', 'Heure pleine')], default='clock_hour', max_length=16)),
                ('market_code', models.CharField(default='NYSE', max_length=16)),
                ('custom_boundaries', models.JSONField(blank=True, default=list)),
                ('custom_analytical_periods', models.JSONField(blank=True, default=list, help_text='[{"key":"midi","label":"Midi","start":"12:00","end":"14:00"}]')),
                ('default_instrument_key', models.CharField(blank=True, default='nasdaq', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_phase_slot_config', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Config créneaux phases marché',
                'verbose_name_plural': 'Configs créneaux phases marché',
            },
        ),
        migrations.CreateModel(
            name='SessionMarketPhaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True)),
                ('instrument_key', models.CharField(db_index=True, max_length=32)),
                ('occurred_at', models.TimeField(db_index=True)),
                ('direction', models.CharField(choices=[('up', 'Haut'), ('down', 'Bas'), ('neutral', 'Neutre')], default='neutral', max_length=8)),
                ('candle_part', models.CharField(choices=[('body', 'Corps'), ('wick', 'Mèche'), ('unknown', 'Inconnu')], default='unknown', max_length=8)),
                ('outcome', models.CharField(choices=[('hold', 'Maintien'), ('reentry', 'Réintégration'), ('unknown', 'Inconnu')], default='unknown', max_length=8)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('live', 'Live'), ('replay', 'Replay')], default='live', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='trades.marketphaseeventdefinition')),
                ('parent_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='trades.sessionmarketphaseblock')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_phase_events', to='trades.tradingaccount')),
                ('trading_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_phase_events', to='trades.tradingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_phase_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement phase marché',
                'verbose_name_plural': 'Événements phases marché',
                'ordering': ['session_date', 'occurred_at'],
                'indexes': [models.Index(fields=['session_date', 'occurred_at'], name='trades_sess_session_0e9513_idx'), models.Index(fields=['parent_block'], name='trades_sess_parent__95ea05_idx'), models.Index(fields=['trading_account', 'session_date', 'instrument_key'], name='trades_sess_trading_cacd47_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sessionmarketphaseblock',
            index=models.Index(fields=['user', 'session_date'], name='trades_sess_user_id_ba950a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmarketphaseblock',
            index=models.Index(fields=['trading_account', 'session_date', 'instrument_key'], name='trades_sess_trading_9ef957_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketphaseeventdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'code'), name='uniq_market_phase_event_def_user_code'),
        ),
        migrations.AddConstraint(
            model_name='marketphaseeventdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True), ('user__isnull', True)), fields=('code',), name='uniq_market_phase_event_def_system_code'),
        ),
        migrations.AddIndex(
            model_name='marketphasedefinition',
            index=models.Index(fields=['user', 'is_active'], name='trades_mark_user_id_f9ee50_idx'),
        ),
        migrations.AddIndex(
            model_name='marketphasedefinition',
            index=models.Index(fields=['is_system', 'is_active'], name='trades_mark_is_syst_882631_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketphasedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'code'), name='uniq_market_phase_def_user_code'),
        ),
        migrations.AddConstraint(
            model_name='marketphasedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True), ('user__isnull', True)), fields=('code',), name='uniq_market_phase_def_system_code'),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            migrations.RunPython.noop,
        ),
    ]
