# Generated by Django 4.2.25 on 2026-07-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0046_session_market_phase_slot_grid'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sessionmarketphaseslotgrid',
            new_name='trades_sess_trading_f4bc23_idx',
            old_name='trades_sess_trading_6f8a1d_idx',
        ),
    ]
