# Generated by Django 4.2.25 on 2026-07-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0048_rename_topsteptrade_to_importedtrade'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='importedtrade',
            name='trades_tops_topstep_29cec5_idx',
        ),
        migrations.RenameIndex(
            model_name='importedtrade',
            new_name='trades_impo_user_id_1d0d9a_idx',
            old_name='trades_tops_user_id_2bf191_idx',
        ),
        migrations.RenameIndex(
            model_name='importedtrade',
            new_name='trades_impo_trading_d80341_idx',
            old_name='trades_tops_trading_0dc281_idx',
        ),
        migrations.RenameIndex(
            model_name='importedtrade',
            new_name='trades_impo_contrac_bc443e_idx',
            old_name='trades_tops_contrac_72d32d_idx',
        ),
        migrations.RenameIndex(
            model_name='importedtrade',
            new_name='trades_impo_trade_t_09ad62_idx',
            old_name='trades_tops_trade_t_23defe_idx',
        ),
        migrations.RenameIndex(
            model_name='importedtrade',
            new_name='trades_impo_trade_d_162569_idx',
            old_name='trades_tops_trade_d_8c6ba6_idx',
        ),
        migrations.RenameIndex(
            model_name='importedtrade',
            new_name='trades_impo_user_id_9c7542_idx',
            old_name='trades_tops_user_id_1afabd_idx',
        ),
        migrations.RenameIndex(
            model_name='importedtrade',
            new_name='trades_impo_user_id_2f054d_idx',
            old_name='trades_tops_user_id_efe20c_idx',
        ),
        migrations.RenameIndex(
            model_name='importedtrade',
            new_name='trades_impo_positio_50033e_idx',
            old_name='trades_tops_positio_fbddb8_idx',
        ),
        migrations.RenameIndex(
            model_name='importedtrade',
            new_name='trades_impo_user_id_3bdbe8_idx',
            old_name='trades_tops_user_id_bb6469_idx',
        ),
        migrations.AddIndex(
            model_name='importedtrade',
            index=models.Index(fields=['external_trade_id'], name='trades_impo_externa_7f0c78_idx'),
        ),
    ]
