# Generated by Django 4.2.25 on 2026-05-03 10:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0033_alter_tradinggoal_goal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingActivityExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_activity_expense_categories', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense (activité trading)',
                'verbose_name_plural': 'Catégories de dépense (activité trading)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradingActivityExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('primary_currency', models.CharField(default='USD', max_length=3, verbose_name='Devise principale')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sous-total')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='TVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total')),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence facture')),
                ('secondary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant secondaire')),
                ('secondary_currency', models.CharField(blank=True, default='', max_length=3, verbose_name='Devise secondaire')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Libellé')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trading_activity.tradingactivityexpensecategory', verbose_name='Catégorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_activity_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Dépense activité trading',
                'verbose_name_plural': 'Dépenses activité trading',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingActivityCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('primary_currency', models.CharField(default='USD', max_length=3, verbose_name='Devise principale')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('secondary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant secondaire')),
                ('secondary_currency', models.CharField(blank=True, default='', max_length=3, verbose_name='Devise secondaire')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('linked_account_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_activity_credits', to='trades.accounttransaction', verbose_name='Transaction de compte liée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_activity_credits', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Crédit activité trading',
                'verbose_name_plural': 'Crédits activité trading',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tradingactivityexpensecategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_trading_activity_category_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='tradingactivityexpense',
            index=models.Index(fields=['user', '-date'], name='trading_act_user_id_9783bb_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingactivityexpense',
            index=models.Index(fields=['user', 'primary_currency'], name='trading_act_user_id_b26bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingactivitycredit',
            index=models.Index(fields=['user', '-date'], name='trading_act_user_id_7717b0_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingactivitycredit',
            index=models.Index(fields=['user', 'primary_currency'], name='trading_act_user_id_926ef1_idx'),
        ),
    ]
