# Generated by Django 4.2.25 on 2026-05-04 19:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingactivitycredit',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='1 unité de devise secondaire = fx_rate unités de devise principale.', max_digits=18, null=True, verbose_name='Taux de change'),
        ),
        migrations.AddField(
            model_name='tradingactivitycredit',
            name='transfer_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant des frais, exprimé dans la devise secondaire.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais de transfert'),
        ),
    ]
