# Generated by Django 4.2.25 on 2026-06-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_activity', '0007_taxpaymentbuiltinlabel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tradingactivitytaxpayment',
            new_name='trading_act_user_id_eeb67f_idx',
            old_name='trading_act_user_id_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='tradingactivitytaxpayment',
            new_name='trading_act_user_id_09aa41_idx',
            old_name='trading_act_user_id_4c9e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='tradingactivitytaxpayment',
            new_name='trading_act_user_id_648838_idx',
            old_name='trading_act_user_id_2b7f8e_idx',
        ),
    ]
