# Generated by Django 4.2.25 on 2026-01-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyjournalentry',
            new_name='daily_journ_user_id_67a455_idx',
            old_name='daily_journ_user_id_7b6ae0_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyjournalentry',
            new_name='daily_journ_trading_7d02ef_idx',
            old_name='daily_journ_trading_e410cf_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyjournalimage',
            new_name='daily_journ_entry_i_71e210_idx',
            old_name='daily_journ_entry_i_23cdb6_idx',
        ),
    ]
