# Generated by Django 4.2.25 on 2026-07-18 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0047_rename_session_slot_grid_index'),
        ('daily_journal', '0002_rename_daily_journ_user_id_7b6ae0_idx_daily_journ_user_id_67a455_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('day', 'Journée'), ('position', 'Position')], max_length=16, verbose_name='Portée')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'ordering': ['scope', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500, verbose_name='Libellé')),
                ('help_text', models.CharField(blank=True, max_length=1000, verbose_name='Aide')),
                ('answer_type', models.CharField(choices=[('boolean', 'Booléen'), ('text', 'Texte'), ('number', 'Nombre'), ('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('scale', 'Échelle'), ('date', 'Date')], max_length=32, verbose_name='Type de réponse')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='daily_journal.questionnaire', verbose_name='Questionnaire')),
            ],
            options={
                'verbose_name': 'Question de questionnaire',
                'verbose_name_plural': 'Questions de questionnaire',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500, verbose_name='Libellé')),
                ('help_text', models.CharField(blank=True, max_length=1000, verbose_name='Aide')),
                ('answer_type', models.CharField(choices=[('boolean', 'Booléen'), ('text', 'Texte'), ('number', 'Nombre'), ('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('scale', 'Échelle'), ('date', 'Date')], max_length=32, verbose_name='Type de réponse')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Ex. min/max/step pour scale/number, max_length pour text', verbose_name='Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_templates', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Modèle de question',
                'verbose_name_plural': 'Modèles de questions',
                'ordering': ['label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplateChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='daily_journal.questiontemplate', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Choix de modèle',
                'verbose_name_plural': 'Choix de modèles',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='daily_journal.questionnairequestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choix de question',
                'verbose_name_plural': 'Choix de questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_questions', to='daily_journal.questiontemplate', verbose_name='Modèle source'),
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('value', models.JSONField(verbose_name='Valeur')),
                ('question_label_snapshot', models.CharField(max_length=500, verbose_name='Libellé (snapshot)')),
                ('answer_type_snapshot', models.CharField(max_length=32, verbose_name='Type (snapshot)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='daily_journal.questionnairequestion', verbose_name='Question')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to='trades.topsteptrade', verbose_name='Trade')),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to='trades.tradingaccount', verbose_name='Compte de trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réponse de questionnaire',
                'verbose_name_plural': 'Réponses de questionnaire',
                'ordering': ['question__order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['user', 'is_active'], name='daily_journ_user_id_269e29_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnairequestion',
            index=models.Index(fields=['questionnaire', 'is_active', 'order'], name='daily_journ_questio_647c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireanswer',
            index=models.Index(fields=['user', 'date', 'trading_account'], name='daily_journ_user_id_548d45_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireanswer',
            index=models.Index(fields=['user', 'trade'], name='daily_journ_user_id_f8fbaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', False), ('trade__isnull', True)), fields=('question', 'trading_account', 'date'), name='uniq_answer_day_question_account_date'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('trade__isnull', False)), fields=('question', 'trade'), name='uniq_answer_position_question_trade'),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['user', 'scope', 'is_active'], name='daily_journ_user_id_5cd07a_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'scope'), name='uniq_active_questionnaire_per_user_scope'),
        ),
    ]
