# Generated by Django 4.2.25 on 2026-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0004_rename_topsteptrade_to_importedtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairequestion',
            name='show_if',
            field=models.JSONField(blank=True, default=None, help_text='{"logic":"and|or","conditions":[{"question_id":…,"operator":"eq|neq","value":…}]}', null=True, verbose_name="Condition d'affichage"),
        ),
    ]
