# Generated by Django 4.2.25 on 2026-10-04

from django.db import migrations, models
from django.db.models.functions import Lower

MAX_LABEL_LENGTH = 500


def _with_suffix(base: str, number: int) -> str:
    suffix = f' ({number})'
    room = MAX_LABEL_LENGTH - len(suffix)
    trimmed = base[:room].rstrip() or base[:room]
    return f'{trimmed}{suffix}'


def plan_template_label_updates(rows):
    """Renvoie les (id, nouveau libellé) à écrire avant la contrainte d'unicité.

    Conserve le plus ancien modèle de chaque (utilisateur, libellé sans casse).
    Les copies sont renommées « libellé (2) », « (3) », etc. Rien n'est supprimé.
    """
    by_user = {}
    for row in rows:
        by_user.setdefault(row['user_id'], []).append(row)

    updates = []
    for user_rows in by_user.values():
        normalized = []
        for row in sorted(user_rows, key=lambda item: item['id']):
            stripped = (row['label'] or '').strip()
            normalized.append({**row, 'stripped': stripped})

        groups = {}
        for row in normalized:
            groups.setdefault(row['stripped'].lower(), []).append(row)

        final_by_id = {}
        occupied = set()
        duplicates = []
        for group in groups.values():
            keeper = group[0]
            final_by_id[keeper['id']] = keeper['stripped']
            occupied.add(keeper['stripped'].lower())
            duplicates.extend(group[1:])

        for row in sorted(duplicates, key=lambda item: item['id']):
            number = 2
            candidate = _with_suffix(row['stripped'], number)
            while candidate.lower() in occupied:
                number += 1
                candidate = _with_suffix(row['stripped'], number)
                if number > 10000:
                    break
            final_by_id[row['id']] = candidate
            occupied.add(candidate.lower())

        for row in normalized:
            new_label = final_by_id[row['id']]
            if new_label != row['label']:
                updates.append((row['id'], new_label))
    return updates


def dedupe_question_template_labels(apps, schema_editor):
    QuestionTemplate = apps.get_model('daily_journal', 'QuestionTemplate')
    rows = list(QuestionTemplate.objects.order_by('id').values('id', 'user_id', 'label'))
    for pk, new_label in plan_template_label_updates(rows):
        QuestionTemplate.objects.filter(pk=pk).update(label=new_label)


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0005_questionnaire_question_show_if'),
    ]

    operations = [
        migrations.RunPython(dedupe_question_template_labels, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='questiontemplate',
            constraint=models.UniqueConstraint(
                Lower('label'),
                models.F('user_id'),
                name='uniq_question_template_label_per_user',
            ),
        ),
    ]
