# Generated by Django 4.2.25 on 2026-09-13 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(db_index=True, max_length=16)),
                ('contract_id', models.CharField(db_index=True, max_length=64)),
                ('timeframe', models.CharField(default='1m', max_length=8)),
                ('start_utc', models.DateTimeField()),
                ('end_utc', models.DateTimeField()),
                ('bars_stored', models.PositiveIntegerField(default=0)),
                ('bars_expected', models.PositiveIntegerField(default=0)),
                ('expected_gap_count', models.PositiveIntegerField(default=0)),
                ('unexpected_missing_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('empty', 'Empty')], db_index=True, default='partial', max_length=16)),
                ('source', models.CharField(blank=True, default='topstepx', max_length=32)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Couverture de bougies',
                'verbose_name_plural': 'Couvertures de bougies',
                'db_table': 'market_data_bar_coverage',
            },
        ),
        migrations.CreateModel(
            name='BarQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('duplicate', 'Duplicate'), ('missing_timestamp', 'Missing timestamp'), ('non_monotonic', 'Non-monotonic'), ('ohlc_inconsistent', 'OHLC inconsistent'), ('invalid_volume', 'Invalid volume'), ('gap', 'Unexpected gap'), ('expected_gap', 'Expected gap'), ('unknown_session_profile', 'Unknown session profile')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=16)),
                ('instrument', models.CharField(blank=True, default='', max_length=16)),
                ('contract_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('timeframe', models.CharField(blank=True, default='1m', max_length=8)),
                ('timestamp_utc', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Issue qualité',
                'verbose_name_plural': 'Issues qualité',
                'db_table': 'market_data_bar_quality_issue',
            },
        ),
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(db_index=True, help_text='Identifiant ProjectX (ex. CON.F.US.ENQ.H25).', max_length=64, unique=True, verbose_name='Contract ID')),
                ('instrument', models.CharField(db_index=True, help_text='Symbole racine (NQ, ES, MGC, …).', max_length=16, verbose_name='Instrument')),
                ('symbol', models.CharField(blank=True, default='', help_text='Nom court API (ex. NQH5).', max_length=32, verbose_name='Symbole court')),
                ('symbol_id', models.CharField(blank=True, default='', help_text='ex. F.US.ENQ', max_length=32, verbose_name='Symbol ID')),
                ('broker_symbol', models.CharField(blank=True, default='', help_text='Segment CON.F.US.XXX (ex. ENQ).', max_length=16, verbose_name='Broker symbol')),
                ('expiry_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expiry_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('listed_from', models.DateField(blank=True, null=True)),
                ('listed_to', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='topstepx', max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrat futures',
                'verbose_name_plural': 'Contrats futures',
                'db_table': 'market_data_futures_contract',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(db_index=True, max_length=16)),
                ('contract_id', models.CharField(blank=True, default='', help_text='Vide = tous les contrats de la période.', max_length=64)),
                ('timeframe', models.CharField(default='1m', max_length=8)),
                ('start_utc', models.DateTimeField()),
                ('end_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('bars_fetched', models.PositiveIntegerField(default=0)),
                ('chunks_done', models.PositiveIntegerField(default=0)),
                ('last_chunk_end', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_download_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job de téléchargement',
                'verbose_name_plural': 'Jobs de téléchargement',
                'db_table': 'market_data_download_job',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(db_index=True, max_length=16)),
                ('symbol', models.CharField(blank=True, default='', max_length=32)),
                ('contract_id', models.CharField(db_index=True, max_length=64)),
                ('timeframe', models.CharField(db_index=True, default='1m', max_length=8)),
                ('timestamp_utc', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.BigIntegerField(default=0)),
                ('ny_date', models.DateField(db_index=True)),
                ('ny_time', models.TimeField()),
                ('session_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_rth', models.BooleanField(default=False)),
                ('is_eth', models.BooleanField(default=False)),
                ('is_us_session', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='topstepx', max_length=32)),
                ('fetched_at', models.DateTimeField()),
                ('extra_raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Bougie historique',
                'verbose_name_plural': 'Bougies historiques',
                'db_table': 'market_data_historical_bar',
                'indexes': [models.Index(fields=['instrument', 'timeframe', 'timestamp_utc'], name='md_bar_instr_tf_ts'), models.Index(fields=['contract_id', 'timeframe', 'timestamp_utc'], name='md_bar_cid_tf_ts'), models.Index(fields=['instrument', 'timeframe', 'ny_date', 'ny_time'], name='md_bar_instr_tf_ny'), models.Index(fields=['instrument', 'timeframe', 'session_date'], name='md_bar_instr_tf_sess')],
            },
        ),
        migrations.AddConstraint(
            model_name='historicalbar',
            constraint=models.UniqueConstraint(fields=('contract_id', 'timeframe', 'timestamp_utc'), name='uniq_historical_bar_contract_tf_ts'),
        ),
        migrations.AddIndex(
            model_name='futurescontract',
            index=models.Index(fields=['instrument', 'expiry_date'], name='market_data_instrum_9a5df6_idx'),
        ),
        migrations.AddIndex(
            model_name='futurescontract',
            index=models.Index(fields=['symbol_id'], name='market_data_symbol__956a69_idx'),
        ),
        migrations.AddField(
            model_name='barqualityissue',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_issues', to='market_data.historicaldownloadjob'),
        ),
        migrations.AddIndex(
            model_name='barcoverage',
            index=models.Index(fields=['instrument', 'contract_id', 'timeframe', 'start_utc', 'end_utc'], name='md_cov_range'),
        ),
        migrations.AddIndex(
            model_name='barcoverage',
            index=models.Index(fields=['contract_id', 'timeframe', 'status'], name='md_cov_status'),
        ),
        migrations.AddIndex(
            model_name='historicaldownloadjob',
            index=models.Index(fields=['user', 'status', '-created_at'], name='market_data_user_id_a82735_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldownloadjob',
            index=models.Index(fields=['instrument', 'status'], name='market_data_instrum_c88e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='barqualityissue',
            index=models.Index(fields=['job', 'issue_type'], name='market_data_job_id_21fadc_idx'),
        ),
        migrations.AddIndex(
            model_name='barqualityissue',
            index=models.Index(fields=['contract_id', 'issue_type'], name='market_data_contrac_13db04_idx'),
        ),
    ]
