# Generated by Django 4.2.25 on 2026-09-13 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_data', '0001_initial_historical_bars'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('hour', models.PositiveSmallIntegerField(default=2, help_text='Heure locale (0–23) dans le fuseau des préférences utilisateur.')),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('last_run_local_date', models.DateField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historical_sync_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réglages sync historique',
                'verbose_name_plural': 'Réglages sync historique',
                'db_table': 'market_data_sync_settings',
            },
        ),
        migrations.AddField(
            model_name='historicaldownloadjob',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], db_index=True, default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='HistoricalSyncTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(db_index=True, max_length=16)),
                ('timeframe', models.CharField(default='1m', max_length=8)),
                ('contract_id', models.CharField(blank=True, default='', help_text='Vide = tous les contrats de la période.', max_length=64)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='market_data.historicalsyncsettings')),
            ],
            options={
                'verbose_name': 'Cible sync historique',
                'verbose_name_plural': 'Cibles sync historique',
                'db_table': 'market_data_sync_target',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='historicalsynctarget',
            constraint=models.UniqueConstraint(fields=('settings', 'instrument', 'timeframe', 'contract_id'), name='uniq_md_sync_target'),
        ),
    ]
