# Generated by Django 4.2.25 on 2026-09-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_data', '0002_sync_settings_and_job_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSyncSchedulerState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('last_tick_ran', models.PositiveIntegerField(default=0)),
                ('last_tick_not_due', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'État du planificateur sync',
                'verbose_name_plural': 'État du planificateur sync',
                'db_table': 'market_data_sync_scheduler_state',
            },
        ),
        migrations.AddField(
            model_name='historicalsyncsettings',
            name='last_finished_at',
            field=models.DateTimeField(blank=True, help_text='Conclusion du dernier run (jobs terminés).', null=True),
        ),
        migrations.AddField(
            model_name='historicalsyncsettings',
            name='last_status',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('up_to_date', 'Up to date')], default='', help_text='Vide = jamais exécuté.', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalsyncsettings',
            name='last_sync_job_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='historicalsyncsettings',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='Déclenchement du dernier run.', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], db_index=True, default='scheduled', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('up_to_date', 'Up to date')], db_index=True, default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job_ids', models.JSONField(blank=True, default=list)),
                ('bars_fetched_total', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Run sync historique',
                'verbose_name_plural': 'Runs sync historique',
                'db_table': 'market_data_sync_run',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='market_data_user_id_56568b_idx')],
            },
        ),
    ]
