# Generated by Django 4.2.25 on 2026-09-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_sync_run_status_and_scheduler_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsyncrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('error', 'Error'), ('up_to_date', 'Up to date')], db_index=True, default='running', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalsyncsettings',
            name='last_status',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('error', 'Error'), ('up_to_date', 'Up to date')], default='', help_text='Vide = jamais exécuté.', max_length=16),
        ),
    ]
